In [109]:
using CSV, Statistics
data = CSV.read("logit_dataset.csv",header=false)

100×3 DataFrames.DataFrame
│ Row │ Column1 │ Column2 │ Column3 │
│     │ Float64 │ Float64 │ Float64 │
├─────┼─────────┼─────────┼─────────┤
│ 1   │ 4.5192  │ 2.6487  │ 1.0     │
│ 2   │ 2.4443  │ 1.5438  │ 1.0     │
│ 3   │ 4.2409  │ 1.899   │ 1.0     │
│ 4   │ 5.8097  │ 2.4711  │ 1.0     │
│ 5   │ 6.4423  │ 3.359   │ 1.0     │
│ 6   │ 5.8097  │ 3.2406  │ 1.0     │
│ 7   │ 6.3917  │ 3.8128  │ 1.0     │
│ 8   │ 6.8725  │ 4.4441  │ 1.0     │
│ 9   │ 6.7966  │ 3.6747  │ 1.0     │
│ 10  │ 8.163   │ 4.7401  │ 1.0     │
⋮
│ 90  │ 2.3937  │ 7.2063  │ 0.0     │
│ 91  │ 1.331   │ 6.5355  │ 0.0     │
│ 92  │ 1.7358  │ 5.4503  │ 0.0     │
│ 93  │ 2.4443  │ 5.8449  │ 0.0     │
│ 94  │ 3.1781  │ 4.8979  │ 0.0     │
│ 95  │ 4.6711  │ 5.8055  │ 0.0     │
│ 96  │ 5.9868  │ 7.3641  │ 0.0     │
│ 97  │ 4.6711  │ 6.2592  │ 0.0     │
│ 98  │ 7.581   │ 8.3703  │ 0.0     │
│ 99  │ 4.6457  │ 8.5676  │ 0.0     │
│ 100 │ 4.6457  │ 8.1676  │ 0.0     │

In [85]:
X = convert(Array,data[[:Column1,:Column2]])
X = normalise(X)
X = hcat(ones(size(X)[1],1),X)

y = convert(Array,data[end])
beta = (zeros(size(X)[2])) 
beta = reshape(beta,1, length(beta))

┌ Warning: `getindex(df::DataFrame, col_inds::Union{AbstractVector, Regex, Not})` is deprecated, use `df[:, col_inds]` instead.
│   caller = top-level scope at In[85]:1
└ @ Core In[85]:1
┌ Warning: `convert(::Type{Array}, df::AbstractDataFrame)` is deprecated, use `convert(Matrix, df)` instead.
│   caller = top-level scope at In[85]:1
└ @ Core In[85]:1
┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[85]:4
└ @ Core In[85]:4


1×3 Array{Float64,2}:
 0.0  0.0  0.0

In [20]:
function normalise(X ::Array)
    """
    normalising the X matrix with min-max normalization
    """
    mins = minimum(X,dims = 1)
    maxs = maximum(X,dims = 1)
    rang = maxs-mins
    norm_X = 1 .- ((maxs .- X)./rang) 
    return norm_X 
end

normalise (generic function with 1 method)

In [90]:
function logistic_func(beta, X)
    """
    logistic(sigmoid) function 
    h(x) = 1/(1+e^(-bx))
    """
    return 1.0./(1 .+ exp.(-X* transpose(beta)))
end

logistic_func (generic function with 1 method)

In [100]:
function log_gradient(beta, X, y)
    """
    logistic gradient function 
    """
    first_calc = logistic_func(beta, X) - reshape(y,size(X)[1],1)
    final_calc = (transpose(first_calc)* X) 
    return final_calc
end

log_gradient (generic function with 1 method)

In [150]:
function cost_func(beta, X, y)
    """ 
    cost function, J 
    """
    log_func_v = logistic_func(beta, X) 
    y = dropdims(y, dims = (findall(size(y) .== 1)...,)) 
    step1 = y .* log.(log_func_v) 
    step2 = (1 - y) .* log.(1 - log_func_v) 
    final = -step1 - step2 
    return mean(final)
end

cost_func (generic function with 1 method)

In [129]:
log_gradient(beta, X, y)

1×3 Array{Float64,2}:
 0.0  -5.06307  9.15966

In [151]:
cost_func(beta, X, y)

MethodError: MethodError: no method matching -(::Int64, ::Array{Float64,1})
Closest candidates are:
  -(::Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}) at int.jl:51
  -(::T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}, !Matched::T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:52
  -(::Union{Int16, Int32, Int64, Int8}, !Matched::BigInt) at gmp.jl:449
  ...

In [145]:
y .* log.(logistic_func(beta, X) )

100×1 Array{Float64,2}:
 -0.6931471805599453
 -0.6931471805599453
 -0.6931471805599453
 -0.6931471805599453
 -0.6931471805599453
 -0.6931471805599453
 -0.6931471805599453
 -0.6931471805599453
 -0.6931471805599453
 -0.6931471805599453
 -0.6931471805599453
 -0.6931471805599453
 -0.6931471805599453
  ⋮                 
 -0.0               
 -0.0               
 -0.0               
 -0.0               
 -0.0               
 -0.0               
 -0.0               
 -0.0               
 -0.0               
 -0.0               
 -0.0               
 -0.0               